### ISSUE TITLE
Command Cannot Access Environment Variables

### ISSUE THREAD

**Issue by arghmeleg** [mvila/on-save#14]
I'd expect the following to work:
```javascript
[
  {
    "files": ["**/*.ex", "**/*.exs"],
    "command": "${PROJECT_ROOT}process_file.sh ${srcFile}"
  }
]
```
Each person on my team exports a `PROJECT_ROOT` variable depending on which OS they're using, but on-save doesn't have that variable set when it runs the command.

**Comment by mvila** [comment]
I double checked. Commands are launched with Node's `child_process.exec()` which should preserve the environment variables.  If your variable `PROJECT_ROOT` is not available, the problem might come from somewhere else. Are you sure that Atom has access to your environment variables?

**Comment by arghmeleg** [comment]
Ah, apparently I just had to start atom with `env atom`. Thank you for double checking! Appreciate all the work you put into this plugin.
