### ISSUE TITLE
Doesn't work and doesn't tell you why

### ISSUE THREAD

**Issue by HDembinski** [mvila/on-save#15]
It has been a frustrating experience so far.

I tried
```
[
  {
    "files": "**/*",
    "command": "echo ${srcFile}"
  }
]
```
and I see no output in the console. When I add deliberate errors in the json format, I can see parsing errors in the console, so I am sure that the file is actually read. I am seeing no effect.

I have an up-to-date Atom and I am working on Linux.

**Comment by mvila** [comment]
Did you set the `showOutput` option to `true` in the [configuration file](https://github.com/mvila/on-save#configuration-file)?

**Comment by HDembinski** [comment]
Yes, I tried that without success. To help debugging what's wrong, could you please add a setting "Verbose" that when enabled makes the package print info to the console. It should tell you whether it found a `.on-save.yml` and its path. It should say which files the "files" filter matched.

**Comment by mvila** [comment]
I am so sorry, but since I don't use Atom anymore, I will not be able to add any new features. I edited the README to mention that this project is now in maintenance mode.
