### ISSUE TITLE
Small Suggestion: Auto-hide successful runs?

### ISSUE THREAD

**Issue by lfgstudios** [mvila/on-save#16]
This is a minor gripe but I'm wondering if there's a way to auto-hide output on successful runs.

I'm using this to run build a webpack project when a file is saved. Main functionality works great, no worries there. But I have to constantly dismiss success alerts. Other tools that show alerts (like the less builder one I use) will auto-hide success alerts after a few seconds. 

It would be great if you could specify in the config file whether or not to hide success alerts and even specify a number of seconds before they're auto-hidden (or just use a single setting where a setting of 0 means don't auto-hide). 

Again, more of a suggestion than anything else. Thanks for making the package in the first place!

**Comment by mvila** [comment]
Hi @KenLFG,

Thanks for your suggestion. I am sorry, but I am quite busy right now, and I am not using Atom anymore (I switched to VS Code).

However, I'll be happy to merge a PR implementing your suggestion.

**Comment by lfgstudios** [comment]
Well, I guess we'll see then. I don't know if I'll have to time to get up to speed on atom's API but maybe if I get a chance to I will. Thanks for the response!

How are you liking VS Code? I used to use VS 2013 and wasn't a fan of the direction they were going with 2015 and 2017, especially since I was doing less and less .Net work.

**Comment by mvila** [comment]
Since Microsoft acquired GitHub, both VS Code and Atom are owned by Microsoft. So my guess is that only one can survive eventually. Ans since VS Code is growing a lot faster than Atom, I think it will win. Basically, this is the reason why I switched. I miss the minimalistic approach of Atom though.
