### ISSUE TITLE
OS-aware configurations

### ISSUE THREAD

**Issue by NbrTDB** [mvila/on-save#18]
This on-save utility seems like a great idea, but I find myself in a situation where I would like on-save to run different commands depending on whether the host operating system is Linux or Windows (essentially, whether to run a shell script or a batch file).

Is there a way (or could a way be added) to define different commands for on-save to run depending on the detected environment? I am imagining something like the following:

```json
[
  {
   "linux": {
     "srcDir": "src",
     "destDir": "dist",
     "files": "**/*.js",
     "command": "babel ${srcFile} --out-file ${destFile}"      
    },
   "windows": {
     "srcDir": "src",
     "destDir": "dist",
     "files": "**/*.js",
     "command": "babel ${srcFile} --out-file ${destFile}"      
    }
  }
]
```

**Comment by mvila** [comment]
I am sorry, but as mentioned in the README, this project is in maintenance mode, and it will not get any new features.

**Comment by NbrTDB** [comment]
Whoops! So it is. Thanks anyway!
