### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by alexisinwork** [mvila/on-save#2]
1. I install package in Atom
2. Create on-save file
3. Save file and nothing happens, even no errors
How to check that it do something?

**Comment by mvila** [comment]
What did you put in your `.on-save.json` file (at the root of your project)?

I just tested the following:

```
[
  {
    "files": "**/*",
    "command": "echo ${srcFile}"
  }
]
```

With such a configuration, each time a file is saved, the corresponding filename is printed in the console (Developer Tools).

**Comment by Brian-Kaplan** [comment]
Yeah works for me. You just have to open the dev console in atom cmd+option+i on mac. I didn't know that existed!!!!!!

**Comment by b-brankovics** [comment]
Hi,

It doesn't work for me either. I have saved the `.on-save.json` in the root of the project with the specification of @mvila and when I save a file and check the *console* I find the following error:
**on-save: Unable to find the project path      ~/.atom/packages/on-save/index.js:51**

Do you have any suggestions?

**Comment by mvila** [comment]
@b-brankovics How do you open the files you are editing? To work correctly, files should not be open directly from Atom with the "Open" command (or by double-clicking them from the Finder). What should do is to open the directory of your project with Atom so it appears in the side bar and from there you can navigate and open your files.

**Comment by b-brankovics** [comment]
Thanks @mvila! I think it is a very useful package that you wrote.

I was trying on Ubuntu with Atom 1.11.1. I saved the file to the root of the package folder I loaded to Atom. Now I tried with OSX and Atom 1.13.0 and now it works. I will check on Ubuntu with an update version.

**Comment by HDembinski** [comment]
Since I am having the same problem now, could you add this information about how to check for errors to the README?
