### ISSUE TITLE
Feature Request: Default configuration file if .on-save.json doesn't exist in project folder

### ISSUE THREAD

**Issue by sebastientaggart** [mvila/on-save#3]
Hello, it would be useful if we could set a default `.on-save.json` file that would trigger if one wasn't found in the local project directory, e.g. a global config file.

**Comment by mvila** [comment]
Hi @sebastientaggart! I just published a new version which change the way `.on-save.json` files are found. Now they don't have to be necessarily located at the root of projects, they can be anywhere in the parent directories of the files you are saving. So, if you want a global config file, you can put it (for example) in your $HOME directory. Another benefit of this change is that we can more easily handle monorepo projects with multiple `.on-save.json` files.

**Comment by sebastientaggart** [comment]
Awesome, looks great, thanks very much!
