### ISSUE TITLE
The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by erwan-lcs** [mvila/on-save#5]
I am randomly getting this error on some files.
![Screenshot](https://i.imgur.com/jWLT21g.png)

I use on-save to copy files to a network share, I added delete before copying over the file but that doesn't improve the situation.

I am on Windows 10, is there any log or has anyone experienced the same issue?

```
[
  {
    "srcDir": "./src",
    "destDir": "\\\\MAC-MINI\\ProjectX\\src",
    "files": "**/*.js",
    "command": "del /f ${destFile} & copy /Y ${srcFile} ${destFile}"
  }
]

```

**Comment by mvila** [comment]
Sorry @erwan-lcs, it seems to be an OS level issue and has nothing to do with on-save.
