### ISSUE TITLE
Feature request: Notification on success

### ISSUE THREAD

**Issue by ManzDev** [mvila/on-save#6]
Hi, Great package. 

Good feature: Notification custom message on finish command.

**Comment by mvila** [comment]
Hi @ManzDev,

Thanks for your feedback, there is now a `successMessage` option! 😄

**Comment by mvila** [comment]
Sorry @ManzDev, I finally dropped the `successMessage` option in favor of `showOutput` which is more powerful (#8).

**Comment by ManzDev** [comment]
Great, I think that, too. 

Thanks!
