### ISSUE TITLE
`successMessage` is counter-intuitive

### ISSUE THREAD

**Issue by quasipedia** [mvila/on-save#8]
This may partly be a matter of taste, but I found the newly introduced `successMessage` setting to be counter-intuitive for a couple of reasons:

- **in programming you normally want to be notified of faulty behaviour**, not successful one (this is why you throw/raise exceptions, or return non-falsy values from processes that fail).
-  **the custom message does not add any information** as if the script runs as planned, the programmer already knows what the expected outcome should be (an can anyway check any variable output with the `showOutput` option now).

My proposal would be to modify this configuration option with a `errorMessage` instead.  Building on the example in the README file (running babel), I would use it like this:

    errorMessage: 'Failed to babelify ${srcFile}'

This way the information:
 
- would be displayed only when it add a critical piece of information,
- would actually provide actionable information to the developer

Bonus point if the message in the notification would link `${srcFile}` to the actual file, and if it offered a button to open a pane and inspect the actual output from the script (sort of "on demand `showOutput`).

Just my 2¢.

[ Unrelated : thanks for implementing #7 so quickly! ]

**Comment by mvila** [comment]
Actually, although not documented, there was already a message in case of error and I've implemented `successMessage` in response to #6. But you raised a good point, it was not clear and for the sake of consistency, I should add an `errorMessage` attribute.

Also, I am thinking about adding a `showError` option (`true` by default) to specify whether the error stream should be displayed or not.

Here's what the documentation might look like:

---

The content of the `.on-save.json` file must be an array of objects with the following properties:

* `srcDir` _(default: `.on-save.json`'s directory)_: The source directory.
* `destDir` _(default: same as `srcDir`)_: The destination directory.
* `files`: The files you want to track. You can use a glob (see [minimatch](https://github.com/isaacs/minimatch)), or an array of globs.
* `command`: The command to execute.
* `successMessage`: A message to display if the command is executed successfully.
* `errorMessage` _(default: `"An error occurred while running the command: ${command}"`)_: A message to display in case of error.
* `showOutput` _(default: `false`)_: A boolean indicating whether the output stream (stdout) should be displayed or not.
* `showError` _(default: `true`)_: A boolean indicating whether the error stream (stderr) should be displayed or not.

In `command`, `successMessage` and `errorMessage`, you can use the following variables:

* `${srcFile}`: The input file.
* `${destFile}`: The output file.
* `${destFileWithoutExtension}`: The output file without the extension.

Finally, in `successMessage` and `errorMessage`, you can use `${command}` which represents the actual executed command.

---

Please tell me what you think.

About your bonus point, it would be great, but I'm a little bit busy these days and I might not be able to implement it. So, PR welcome! 😄

**Comment by quasipedia** [comment]
Choosing the feature set and the syntax is very much the part where the maintainer should claim their ownership, take the lead, and try to keep things consistent.  That said, **my _personal_ preference would be to simply drop `successMessage` and `errorMessage` completely if you implement `showOutput` and `showError` separately**.

This is because they are totally redundant now, given that:

- any formatting and info they would provide, could be provided by the script itself (which in turns have access to the complete set of variables the command is using),
- the logic error/success would be already implemented in the separate handling of `stdout` and `stderr`
- I love orthogonality of commands and features :)

Again though: an API is as much a rational choice as a stylistic one, so I would invite you to go with whatever feels right for you and keep you motivated maintaining the extension!

Thanks again for the prompt answer! :)

**Comment by mvila** [comment]
Thanks @quasipedia, I totally agree with you, it is a lot simpler without `successMessage` (and `errorMessage`)! So I dropped it in version 2.2. It is a breaking change but release 2.1 has only be available for 2 days, so I guess nobody has noticed about it! 🙏
